name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x map-sample/gradlew && chmod +x navigation-sample/gradlew 
    - name: Build map-sample with Gradle
      run: cd map-sample && ./gradlew build
    - name: Build navigation-sample with Gradle
      run: cd navigation-sample && ./gradlew build
    - name: Calculate map-sample APK size difference
      id: size-diff-map
      uses: jacobras/size-diff-action@v2
      with:
        path: map-sample/app/build/outputs/apk/release/app-release-unsigned.apk
    - name: Comment map-sample size difference on PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: size-diff-map
        message: |
            ### APK diff: `map-sample app-release-unsigned.apk`
            
            ${{ steps.size-diff-map.outputs.summary }}
    - name: Calculate navigation-sample APK size difference
      id: size-diff-navigation
      uses: jacobras/size-diff-action@v2
      with:
        path: navigation-sample/app/build/outputs/apk/release/app-release-unsigned.apk
    - name: Comment navigation-sample size difference on PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: size-diff-map
        message: |
            ### APK diff: `navigation-sample app-release-unsigned.apk`
            
            ${{ steps.size-diff-navigation.outputs.summary }}

